In [ ]:
import pandas as pd
import numpy as np
import datetime

In [ ]:
df = pd.read_csv('/content/googleplaystore(impure).csv')

In [ ]:
df.sample(5)

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3432,3432,Tropical Beach Live Wallpaper,PERSONALIZATION,4.0,11343,8.4M,"1,000,000+",Free,0,Everyone,Personalization,22-May-18,18,4.1 and up
931,931,Netflix,ENTERTAINMENT,4.4,5456599,Varies with device,"100,000,000+",Free,0,Teen,Entertainment,31-Jul-18,Varies with device,Varies with device
8132,8132,Security Camera CZ,HOUSE_AND_HOME,4.4,137,19M,"10,000+",Free,0,Everyone,House & Home,17-Jul-18,1.1.10,4.1 and up
5450,5450,AP® Guide,FAMILY,5.0,3,2.1M,"1,000+",Free,0,Everyone,Education,31-Jul-17,1.3,4.0.3 and up
9672,9672,Masha and the Bear - Hair Salon and MakeUp Games,FAMILY,NaN,1,83M,100+,Paid,$2.49,Everyone,Role Playing;Education,5-Mar-18,1.0.1,4.1 and up

In [ ]:
df.shape

(10841, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10841 non-null  int64
 1   App             10841 non-null  object
 2   Category        10841 non-null  object
 3   Rating          9367 non-null   float64
 4   Reviews         10841 non-null  object
 5   Size            10841 non-null  object
 6   Installs        10841 non-null  object
 7   Type            10840 non-null  object
 8   Price           10841 non-null  object
 9   Content Rating  10840 non-null  object
 10  Genres          10841 non-null  object
 11  Last Updated    10841 non-null  object
 12  Current Ver     10833 non-null  object
 13  Android Ver     10838 non-null  object
dtypes: float64(1), int64(1), object(12)
memory usage: 1.2+ MB

In [ ]:
df.isnull().sum()

Unnamed: 0           0
App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [ ]:
df.describe()

         Unnamed: 0       Rating
count  10841.000000  9367.000000
mean    5420.000000     4.193338
std     3129.671468     0.537431
min        0.000000     1.000000
25%     2710.000000     4.000000
50%     5420.000000     4.300000
75%     8130.000000     4.500000
max    10840.000000    19.000000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.drop(columns='Unnamed: 0', inplace= True)

In [ ]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors= 'coerce')

<ipython-input-12-e95353d0ad67>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors= 'coerce')

In [ ]:
df['Last Updated'] = df['Last Updated'].dt.strftime('%Y-%m-%d')

In [ ]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors= 'coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9360 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9360 non-null   object
 1   Category        9360 non-null   object
 2   Rating          9360 non-null   float64
 3   Reviews         9360 non-null   object
 4   Size            9360 non-null   object
 5   Installs        9360 non-null   object
 6   Type            9360 non-null   object
 7   Price           9360 non-null   object
 8   Content Rating  9360 non-null   object
 9   Genres          9360 non-null   object
 10  Last Updated    9360 non-null   datetime64[ns]
 11  Current Ver     9360 non-null   object
 12  Android Ver     9360 non-null   object
dtypes: datetime64[ns](1), float64(1), object(11)
memory usage: 1023.8+ KB

In [ ]:
df['Installs'] = df['Installs'].str.replace(',', '').str.replace('+', '')

In [ ]:
df['Installs'] = df['Installs'].astype(int)

In [ ]:
df['Reviews'] = df['Reviews'].str.replace('M', '').str.replace(',', '').astype(int) * 1000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9360 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9360 non-null   object
 1   Category        9360 non-null   object
 2   Rating          9360 non-null   float64
 3   Reviews         9360 non-null   int64
 4   Size            9360 non-null   object
 5   Installs        9360 non-null   int64
 6   Type            9360 non-null   object
 7   Price           9360 non-null   object
 8   Content Rating  9360 non-null   object
 9   Genres          9360 non-null   object
 10  Last Updated    9360 non-null   datetime64[ns]
 11  Current Ver     9360 non-null   object
 12  Android Ver     9360 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 1023.8+ KB

In [ ]:
df['Price'] = df['Price'].str.replace('$', '').astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9360 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9360 non-null   object
 1   Category        9360 non-null   object
 2   Rating          9360 non-null   float64
 3   Reviews         9360 non-null   int64
 4   Size            9360 non-null   object
 5   Installs        9360 non-null   int64
 6   Type            9360 non-null   object
 7   Price           9360 non-null   float64
 8   Content Rating  9360 non-null   object
 9   Genres          9360 non-null   object
 10  Last Updated    9360 non-null   datetime64[ns]
 11  Current Ver     9360 non-null   object
 12  Android Ver     9360 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 1023.8+ KB

In [ ]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [ ]:
df.to_csv('playstore.csv', index = False)